renegade_contracts: darkpool: add verifiaction polling methods
renegade-fi/renegade-stylus-contracts pull request #57
Opened 2023-08-12 19:52 UTC by akirillo

This PR introduces "polling" methods accompanying `new_wallet`, `update_wallet`, and `process_match`, which call out to the underlying `verifier.step_verification` method and, when it completes, handle the merkle / nullifier set updating logic (should the proof verify).

As such, calling `new_wallet` / etc. will simply enqueue the verification jobs, and to drive them forward, one must call `poll_new_wallet` / etc.

A deliberate unknown left here is whether or not enqueueing the 6 verification jobs necessary for `process_match` will be possible within a single transaction. For full size circuits, almost definitely not, but this is something I intend to iterate on, for now optimistically assuming that it will work.

The darkpool Cairo tests are now excluded from the `testing` module since they will all need to be ported over to e2e tests (since they now invoke the verifier, they will need a proof generated from `mpc-bulletproof` as input).

The e2e test updates are coming in a separate PR.

2023-08-12 21:36 UTC, joeykraut requested changes, later dismissed
Structurally looks good, a few bugs to clear up

2023-08-12 21:36 UTC, joeykraut commented on src/darkpool.cairo
> +        wallet_share_commitment: Scalar,
Why do we need these calldata elements? They seem redundant, and we should aim to keep our interface lean

2023-08-12 21:36 UTC, joeykraut commented on src/darkpool.cairo
> +        wallet_share_commitment: Scalar,
same below

2023-08-12 21:36 UTC, joeykraut commented on src/darkpool.cairo
> +                    _mark_wallet_updated(ref self, wallet_blinder_share);
I see why you added these to calldata. We should use the ones in the proof. One security check that's missing here is that these calldata commitments and blinder shares match those given in the proof. Instead, let's avoid needing this check and use the fields on the proof directly.

2023-08-12 21:36 UTC, joeykraut commented on src/darkpool.cairo
> +                    nullifier_set.mark_nullifier_used(old_shares_nullifier);
Same as above, we should *not* be using the raw calldata.

2023-08-12 21:36 UTC, joeykraut commented on src/darkpool.cairo
> +                    let new_root = merkle_tree.insert(party_1_wallet_share_commitment);
calling out here the same as above for completeness

2023-08-12 22:24 UTC, akirillo commented on src/darkpool.cairo
> +                    _mark_wallet_updated(ref self, wallet_blinder_share);
Hmm... so in that case, we'd be inserting the witness commitments submitted alongside the proof into the merkle tree and nullifier set (as opposed to plaintext public inputs), right? I can definitely grab those out of `witness_commitments` and remove these calldata elements from all of the interfaces, but I think we'd still need a check that those witness commitments are the same ones submitted to the verifier. I'm not sure the best way to do this, may take a bit more design (and prob just using a bit more contract storage), which I can do and then put this PR back up.

Does this track / am I misunderstanding?

2023-08-14 18:34 UTC, akirillo commented
@joeykraut will fix formatting + squash after review, if i do this now then the rebase will bork your ability to review just the last commit

2023-08-14 22:08 UTC, joeykraut approved these changes

2023-08-14 22:08 UTC, joeykraut commented on src/darkpool.cairo
> +        StorageAccessSerdeWrapper<ProcessMatchCallbackElems>>,
Can we rename this to be a bit more clear what's going on, and expand the comments with a description of how these values are reused.

Re: naming; a better name might be `new_wallet_public_inputs` or `new_wallet_state_elements`, something of that sort

2023-08-14 22:08 UTC, joeykraut commented on src/darkpool.cairo
> +        /// - `wallet_share_commitment`: The commitment to the new wallet's shares
out of date docstring

2023-08-14 22:08 UTC, joeykraut commented on src/darkpool.cairo
> +        /// - `external_transfers`: The external transfers (ERC20 deposit/withdrawal)
same as above, let's just have a quick pass over the docstrings and make sure they match the interfaces after the update

2023-08-14 22:08 UTC, joeykraut commented on src/darkpool.cairo
> +            verification_job_ids: Array<felt252>,
do we check anywhere that these are unique wrt other contract calls? If not we should, this seems especially important given that for this call only the first ID is used to index state

2023-08-14 22:29 UTC, akirillo commented on src/darkpool.cairo
> +        StorageAccessSerdeWrapper<ProcessMatchCallbackElems>>,
Haha, i actually started with `public_inputs` but decided against it since it's not *all* of the public inputs. I kind of like `callback_elems` since it feels most to the point - these are used in the "callback" logic after polling is complete. Will update comments to use this verbage as well.

2023-08-14 22:33 UTC, akirillo commented on src/darkpool.cairo
> +            verification_job_ids: Array<felt252>,
In the verifier contract(s), we assure that each new `verification_job_id` is unique. So in the initial enqueuing of the verification job in `new_wallet`, `update_wallet`, `process_match`, the tx would revert if the verification job(s) were duplicates. In subsequent calls to the `poll_*` functions, it feels fair to put the responsibility onto the user to remember & reuse the correct verification job ids (not a security violation, may just drive forward someone else's verification / get a reverted tx)

2023-08-14 22:38 UTC, joeykraut commented on src/darkpool.cairo
> +        StorageAccessSerdeWrapper<ProcessMatchCallbackElems>>,
I'd prefer state elements in that case, it's unclear what "callback" means to a third party

2023-08-14 22:47 UTC, merged